### PR TITLE
80 add news to app & fragments bug fix

### PR DESCRIPTION
**Pull request by Araknor99**
News have been added and the bugfix for the fragments is implemented.

Screenshots:
screenshot_2017-10-18-11-51-14
screenshot_2017-10-18-11-51-19
screenshot_2017-10-18-11-51-37

### CODE REVIEW

**Comment by jprberlin** [comment]
Should we use a white background in detail view?

**Comment by jprberlin** [comment]
And I would opt for putting the date always below the headline and make the table rows height dynamic...

**Comment by Araknor99** [comment]
I think a white background for the detail view would be better, so yes. For the dynamic height I'd think of cutting the text by the first empty line, with a max line count of five.

**Comment by Araknor99** [comment]
Oh, In the last commit I forgot to to say that I also made the height dynamic.

**Comment by jprberlin** [comment]
Will make ne PR from internal so Encryeped Build Vars can be used

**Pull request closed without merging**
