### PR TITLE
add particle anim

### PR DESCRIPTION
**Pull request by pinussilvestrus**

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
[Integrate Particles](https://trello.com/c/9eInbDfQ/77-integrate-particles)

**Comment by pinussilvestrus** [comment]
ezgif com-video-to-gif

**Comment by pinussilvestrus** [comment]
fix #39

**Comment by kremer-io** [comment]
As discussed with iOS team, we're trying to have similar designs. Therefore, in the first steps, no custom animations are needed.

**Comment by pinussilvestrus** [comment]
:(

**Pull request closed without merging**
