### PR TITLE
69 show course and class folders in file manager

### LINKED ISSUE #69: Show course and class folders in file-manager

### PR DESCRIPTION
**Pull request by JonasWanke**
Fixes #69 and #99:
- Added FileOverviewFragment for selecting between personal and course folders (with their respective colors)
- FileFragment now includes breadcrumbs
- Restyled directory and file item layouts to be less high. Delete icon is now in an overflow menu (rename and move can be placed there too), and files have icons based on their type.
- File upload is now working
- Empty directories have an indicator
- A new folder can be created

_Note: The screenshots were taken using different screen resolutions_

FileOverviewFragment | Breadcrumbs
:---: | :---:
image | image

Empty folder | Write actions
:---: | :---:
image | image

### CODE REVIEW

**Comment by janrenz** [comment]
This looks great. On the display list do we have two functions? Open (via intend) and download? Then maybe the open in function should be visible as well and not just implicit.

**Comment by JonasWanke** [comment]
@janrenz Currently the file is opened directly when tapping on it, and is saved to the downloads folder when clicking the icon. I'm not sure whether an additional button for opening would make sense as that action seems intuitive and is visually supported by a ripple effect.

**Comment by janrenz** [comment]
@tobiasrohloff Opinions on this one?

**Comment by kremer-io** [comment]
The first back button click is ignored, the second crashes the app.

```
java.lang.IllegalStateException: The view is currently not attached. Call #sendToView(ViewAction) instead
       at org.schulcloud.mobile.ui.base.BasePresenter.getViewOrThrow(BasePresenter.java:100)
       at org.schulcloud.mobile.ui.main.MainPresenter.showFragment(MainPresenter.java:165)
       at org.schulcloud.mobile.ui.main.MainPresenter.onBackPressed(MainPresenter.java:181)
       at org.schulcloud.mobile.ui.main.MainActivity.onBackPressed(MainActivity.java:123)
       at android.app.Activity.onKeyUp(Activity.java:2965)
       at android.view.KeyEvent.dispatch(KeyEvent.java:2712)
       at android.app.Activity.dispatchKeyEvent(Activity.java:3257)
       at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:541)
       at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
       at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:319)
       at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
       at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:351)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4714)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4586)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4181)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4147)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4274)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4155)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4331)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4181)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4147)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4155)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4181)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4147)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4307)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4468)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2435)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1998)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1989)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2412)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(Native Method)
       at android.os.MessageQueue.next(MessageQueue.java:325)
       at android.os.Looper.loop(Looper.java:142)
       at android.app.ActivityThread.main(ActivityThread.java:6541)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by JonasWanke** [comment]
@kremer-io I know, that is a general problem of the app which I fixed in #114. Could you please install that branch and try to reproduce the bug?

**Comment by kremer-io** [comment]
@JonasWanke Ok, #114 is merged.

**Comment by janrenz** [comment]
HI, again some conflicts here we need to fix

**Comment by JonasWanke** [comment]
@janrenz #114 was based on this branch and therefore contained all changes from here, so I will close this PR.

**Pull request closed without merging**
