### PR TITLE
Split DataManager and DatabaseHelper

### PR DESCRIPTION
**Pull request by Araknor99**
Split DataManager and DatabaseHelper into individual classes.

### CODE REVIEW

**Comment by kremer-io** [comment]
@Araknor99 This PR is referencing #66, right?

**Comment by Araknor99** [comment]
@kremer-io Yes it is.

**Comment by kremer-io** [comment]
I just approved another PR, now we've conflicts here.

**Comment by Araknor99** [comment]
It should be fixed now.

**Comment by janrenz** [comment]
@kremer-io is this ready to be merged?

**Pull request merged**
